spring.application.name=FactuStock

spring.datasource.url=jdbc:postgresql://localhost:5432/factustock
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver


# Configuración de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Activar log de SQL
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
# application.properties
