spring.application.name=FactuStock



spring.datasource.url=jdbc:postgresql://localhost:5432/factustock
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logo.directory.path=src/main/resources/logo-img/
spring.jackson.serialization.indent_output=true
spring.jackson.stream.write_constraints.max_nesting_depth=4000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=factustock.idp@gmail.com
spring.mail.password=xudn flml ruzo ozvv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

logging.level.org.springframework.mail=DEBUG
spring.profiles.active=dev
